<a href="https://colab.research.google.com/github/spicy-adobo/LIS-4-5693/blob/main/Copy_of_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing libraries

In [ ]:
import pandas as pd
import altair as alt
from vega_datasets import data as vega_data

Loading Seattle Circulation data

In [ ]:
import requests
import io

url = "https://raw.githubusercontent.com/manika-lamba/SP26-LIS4_5693/refs/heads/main/lab-assignments/lab-3/Seattle-Library_2015-2021.csv"
response = requests.get(url)
response.raise_for_status() # Raise an exception for HTTP errors
text = response.text

Saving as dataframe

In [ ]:
seattle_df = pd.read_csv(io.StringIO(text))
seattle_df.head()

,Title,Creator,MaterialType,Checkouts,CheckoutYear,CheckoutMonth,Publisher,PublicationYear,Subjects,UsageClass,CheckoutType
0,Frog and toad all year / by Arnold Lobel.,"Lobel, Arnold",BOOK,34,2016,10,"Harper & Row,",c1976.,"Friendship Fiction, Frogs Juvenile fiction, To...",Physical,Horizon
1,"My brilliant friend : childhood, adolescence /...","Ferrante, Elena",BOOK,110,2016,10,"Europa Editions,",2012,"Friendship Fiction, Naples Italy Fiction",Physical,Horizon
2,Star trek [videorecording] / Paramount ; Spygl...,NaN,VIDEODISC,36,2016,10,"Paramount Home Entertainment,",c2009.,"Kirk James T 2233 2371 Drama, Spock Mr Drama, ...",Physical,Horizon
3,The Man in the High Castle,Philip K. Dick,EBOOK,63,2016,10,Houghton Mifflin Harcourt Trade and Reference,2012,"Fiction, Science Fiction",Digital,OverDrive
4,"The Fifth Season: Broken Earth Series, Book 1",N. K. Jemisin,EBOOK,44,2016,10,"Hachette Digital, Inc.",2015,"Fantasy, Fiction, Thriller",Digital,OverDrive

## Exercise

Task One and Two: Visualizing 2 Different Columns with Differing Altair Marks

In [ ]:
seattle_df

,Title,Creator,MaterialType,Checkouts,CheckoutYear,CheckoutMonth,Publisher,PublicationYear,Subjects,UsageClass,CheckoutType
0,Frog and toad all year / by Arnold Lobel.,"Lobel, Arnold",BOOK,34,2016,10,"Harper & Row,",c1976.,"Friendship Fiction, Frogs Juvenile fiction, To...",Physical,Horizon
1,"My brilliant friend : childhood, adolescence /...","Ferrante, Elena",BOOK,110,2016,10,"Europa Editions,",2012,"Friendship Fiction, Naples Italy Fiction",Physical,Horizon
2,Star trek [videorecording] / Paramount ; Spygl...,NaN,VIDEODISC,36,2016,10,"Paramount Home Entertainment,",c2009.,"Kirk James T 2233 2371 Drama, Spock Mr Drama, ...",Physical,Horizon
3,The Man in the High Castle,Philip K. Dick,EBOOK,63,2016,10,Houghton Mifflin Harcourt Trade and Reference,2012,"Fiction, Science Fiction",Digital,OverDrive
4,"The Fifth Season: Broken Earth Series, Book 1",N. K. Jemisin,EBOOK,44,2016,10,"Hachette Digital, Inc.",2015,"Fantasy, Fiction, Thriller",Digital,OverDrive
...,...,...,...,...,...,...,...,...,...,...,...
282282,The Fire Next Time,James Baldwin,EBOOK,23,2021,5,"Random House, Inc.",2013,"Sociology, African American Nonfiction, Nonfic...",Digital,OverDrive
282283,"Girl, woman, other / Bernardine Evaristo.","Evaristo, Bernardine, 1959-",BOOK,22,2021,5,"Black Cat, an imprint of Grove Atlantic,",[2019],"Women Black Great Britain Fiction, Great Brita...",Physical,Horizon
282284,Your Money or Your Life: 9 Steps to Transformi...,Vicki Robin,AUDIOBOOK,30,2021,5,Books on Tape,2018,"Business, Finance, Self-Improvement, Nonfiction",Digital,OverDrive
282285,Harry Potter and the Order of the Phoenix: Har...,J. K. Rowling,EBOOK,32,2021,5,Pottermore,2012,"Juvenile Fiction, Juvenile Literature",Digital,OverDrive
282286,Thick: And Other Essays,Tressie McMillan Cottom,EBOOK,22,2021,5,Lightning Source Inc,2019,"Essays, Sociology, Nonfiction",Digital,OverDrive

Visualizing Usage Class counts over the years

In [ ]:
seattle_grouped_by_usage = seattle_df.groupby(['CheckoutYear', 'UsageClass']).size().reset_index(name='counts')

alt.Chart(seattle_grouped_by_usage).mark_line(point=True).encode(
    x=alt.X('CheckoutYear:O', title='Checkout Year'),
    y=alt.Y('counts:Q', title='Count'),
    color=alt.Color('UsageClass:N', title='Usage Class'),
).properties(
    title='Physical vs Digital Checkouts Over the Years'
)

alt.Chart(...)

Visualizing Checkouts by Month per Publisher

In [ ]:
alt.data_transformers.disable_max_rows()

alt.Chart(seattle_df).mark_circle(size=80).encode(
    x=alt.X('CheckoutMonth:O', title='Checkout Month'),
    y=alt.Y('count():Q', title='Number of Checkout Records'),
    color=alt.Color('Publisher:N', title='Publisher'),
)

Task Three Adding Interactivity

Adding zooming to Visualization 1

In [ ]:
alt.Chart(seattle_grouped_by_usage).mark_line(point=True).encode(
    x=alt.X('CheckoutYear:O', title='Checkout Year'),
    y=alt.Y('counts:Q', title='Count'),
    color=alt.Color('UsageClass:N', title='Usage Class'),
).properties(
    title='Physical vs Digital Checkouts Over the Years'
).interactive()

alt.Chart(...)

Adding tooltips and interactivity to Visualization 2

In [ ]:
input_dropdown = alt.binding_select(
    options=sorted(seattle_df['Publisher'].dropna().unique()),
    name='Publisher '
)

selection = alt.selection_point(
    fields=['Publisher'],
    bind=input_dropdown
)

color = (
    alt.when(selection)
    .then(alt.Color('Publisher:N').legend(None))
    .otherwise(alt.value('lightgray'))
)
alt.Chart(seattle_df).mark_circle(size=80).encode(
    x=alt.X('CheckoutMonth:O', title='Checkout Month'),
    y=alt.Y('count():Q', title='Number of Checkout Records'),
    color=color,
    tooltip=['Publisher', 'CheckoutMonth', 'count()']
).add_params(
    selection
).properties(
    title='Count of Checkouts by Month for Each Publisher'
)

Task Four: Horizontal Concatenation

Naming Charts

In [ ]:
viz1 = alt.Chart(seattle_grouped_by_usage).mark_line(point=True).encode(
    x=alt.X('CheckoutYear:O', title='Checkout Year'),
    y=alt.Y('counts:Q', title='Count'),
    color=alt.Color('UsageClass:N', title='Usage Class'),
).properties(
    title='Physical vs Digital Checkouts Over the Years'
)
viz2 = alt.Chart(seattle_df).mark_circle(size=80).encode(
    x=alt.X('CheckoutMonth:O', title='Checkout Month'),
    y=alt.Y('count():Q', title='Number of Checkout Records'),
    color=alt.Color('Publisher:N', title='Publisher'),
)

Combining

In [ ]:
alt.hconcat(viz1,viz2)

Task 5:

What went well? The initial beginning and figuring out the interactivities and the fourth task.
What challenges did you encounter? I really struggled trying to figure out what visualizations I could make without the material type column. My brainstorming kept going back to material types. I also had issues with making my own charts as it was a lot of trial and error in trying to get what I was visualizing in my head/what I wanted to compare actually onto the screen. A lot of brainstorming beyond my current capabilities, but Google and YouTube are helpful.